# Generated by Django 5.2.3 on 2025-07-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlqrcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
